# -*- coding: utf-8 -*-
"""Student's preference in job.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SFfDpHLiGMPujt0uOR7PQc7qNGSN3S13

# **Student's preference in job**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

from google.colab import files
uploaded = files.upload()

#Reading the csv file
Job=pd.read_csv("JobSurveyIndia.csv")
Job.head()

Job.info()

"""There is no null values

## **Data cleaning**
"""

Job.drop(columns='Unnamed: 0',inplace=True)

Job['Employment Background'] = Job['Employment Background'].apply(lambda x:'Art' if x=='Art ' else x )
Job['Degree'] = Job['Degree'].apply(lambda x:'Art' if x=='Art ' else x )
Job['Public Dealing'] = Job['Public Dealing'].apply(lambda x:'Art' if x=='Art ' else x )

"""## **Insights**"""

sec1= Job.loc[Job['Employment Sector']=='Private Sector']
sec2= Job.loc[Job['Employment Sector']=='Government Sector']
sec3= Job.loc[Job['Employment Sector']=='Entrepreneurship']

private= 100*(len(sec1)/len(Job))
govt= 100*(len(sec2)/len(Job))
entre= 100*(len(sec3)/len(Job))

print(private,'% of Students Prefer to be in Private Sector.')
print(govt,'% of Students Prefer to be in Government Sector.')
print(entre,'% of Students Prefer to be a Entrepreuner.')

sec1= Job.loc[Job['Employment Background']=='Technical']
sec2= Job.loc[Job['Employment Background']=='Non-Technical']
sec3= Job.loc[Job['Employment Background']=='Art']

Tech= round(100*(len(sec1)/len(Job)),2)
Non_Tech= round(100*(len(sec2)/len(Job)),2)
Art= round(100*(len(sec3)/len(Job)),2)

print(Tech,'% of Students Prefer to go into Technical Field.')
print(Non_Tech,'% of Students Prefer to go into Non-Technical Field.')
print(Art,'% of Students Prefer to go into Art Field.')

"""## **Vizualization**"""

fig=plt.figure(figsize=(8,5))

sns.countplot(x='Employment Sector',data=Job,palette='RdPu')
plt.title("Student's Preference in Different Employment Sectors",fontsize=20,fontweight='bold')
plt.xlabel("Employment Sector",fontsize=15,fontweight='bold')
plt.ylabel("Count",fontsize=15,fontweight='bold')

plt.xticks(fontweight='bold',fontsize=12)
plt.yticks(fontweight='bold',fontsize=12)
plt.show()

"""## **Number Of Students Preferring Different Type of Field for Job.**"""

fig= plt.figure(figsize=(8,5))

sns.countplot(x='Employment Background',data=Job)

plt.title("Student's preference in Employment Background",fontsize=20,fontweight='bold')
plt.xlabel("Employment Background",fontsize=15,fontweight='bold')
plt.ylabel("Count",fontsize=15,fontweight='bold')

plt.xticks(fontweight='bold',fontsize=12)
plt.yticks(fontweight='bold',fontsize=12)
plt.show()

"""## **Number Of Students who are Comfortable with Public Dealing**"""

fig= plt.figure(figsize=(8,5))

sns.countplot(x='Public Dealing',data=Job)

plt.title("Student's comfort in Public Dealing",fontsize=20,fontweight='bold')
plt.xlabel("Public Dealing",fontsize=15,fontweight='bold')
plt.ylabel("Count",fontsize=15,fontweight='bold')

plt.xticks(fontweight='bold',fontsize=12)
plt.yticks(fontweight='bold',fontsize=12)
plt.show()

"""## **Number Of Students Persuing the Degree in which they want to make their Career**"""

fig= plt.figure(figsize=(8,5))

sns.countplot(x='Degree',data=Job)

plt.title("Students Persuing Respective Degrees in which they want their Career",fontsize=20,fontweight='bold')
plt.xlabel("Degree",fontsize=15,fontweight='bold')
plt.ylabel("Count",fontsize=15,fontweight='bold')

plt.xticks(fontweight='bold',fontsize=12)
plt.yticks(fontweight='bold',fontsize=12)
plt.show()

"""## **Number Of Students Preferring Number of Days to Work in a Week**"""

fig= plt.figure(figsize=(8,5))

sns.countplot(x='IdealNumberOfWorkdays',data=Job)

plt.title("Ideal Number Of Workdays in a Week",fontsize=20,fontweight='bold')
plt.xlabel("Number of Workdays",fontsize=15,fontweight='bold')
plt.ylabel("Count",fontsize=15,fontweight='bold')

plt.xticks(fontweight='bold',fontsize=12)
plt.yticks(fontweight='bold',fontsize=12)
plt.show()

"""## **Number Of Students Preferring an Ideal Salary Per Year**"""

ig= plt.figure(figsize=(8,5))

sns.countplot(x='IdealYearlyIncome',data=Job)

plt.title("Students Preferning Ideal Income Yearly",fontsize=20,fontweight='bold')
plt.xlabel("Ideal Income",fontsize=15,fontweight='bold')
plt.ylabel("Count",fontsize=15,fontweight='bold')

plt.xticks(fontweight='bold',fontsize=12)
plt.yticks(fontweight='bold',fontsize=12)
plt.show()

sns.catplot(x='Employment Background',data=Job,col='Employment Sector',kind='count',aspect=1)

plt.show()

sns.catplot(data=Job,x='Employment Sector',kind='count',hue='Public Dealing',aspect=1)

sns.catplot(x='Employment Background',data=Job,col='Employment Sector',kind='count',hue='Public Dealing',aspect=1)
plt.show()

sns.catplot(x='Employment Background',data=Job,col='Employment Sector',kind='count',hue='Degree',aspect=1)
plt.show()

sns.catplot(x='Employment Background',data=Job,col='Employment Sector',kind='count',hue='IdealYearlyIncome',aspect=1)
plt.show()

sns.catplot(x='Employment Background',data=Job,col='Employment Sector',kind='count',hue='IdealNumberOfWorkdays',aspect=1)
plt.show()

"""### **CONCLUSION**
1. We Can easily see that most of the students Prefer to have a Government Job once graduated with Non-Technical Background.

2. Students Who Want to make Career in Non-Technical Background are often choose to be in Goverment Sector Rather than in Private Sector or be an Entreprenuer.

3. Students Who want to be in Government Sector are more Confortable with Public Dealing than Students preferring Private Sector.It maybe because Most of the Students with Non-Technical Background Prefer to be in government Sector.

4. Students Who want to go in Private Sector are Persuing the Degree for their Respective Career. And Students Who wants to Be in Arts and want to start their own Start-Up are also persuing The Respective Degrees. It maybe because in Public Sector a degree of the perticular is a must.

5. Students in Arts Love to work that's Why some of them recommend to work all the days in a week whether the average days are 5 days per week.Also the Students who wants to be a Entrepreneur also recommend more than average days to work per week.

6.Students with Technical Background And in Public Sector expects more than Average Salary.
"""